"""empty message

Revision ID: 31d486d06c0a
Revises: cae58ee6d1a7
Create Date: 2023-04-07 19:02:47.885051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d486d06c0a'
down_revision = 'cae58ee6d1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boulders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boulders', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
